openapi: 3.0.3
info:
  title: Social Network API
  version: 1.0.0

paths: 
  /users/{userId}/friends/{friendId}:
    post:
      summary: Add friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: friendId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "201":
          description: Friend added
        "400":
          description: Invalid request
        "404":
          description: User not found

    delete:
      summary: Delete friend
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: friendId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204": 
          description: Friend removed
        "404": 
          description: Friendship not found
  
  /users/{userId}/friends:
    get:
      summary: List all friends
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: Number of items to return
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: Friends listed
        "404":
          description: User not found
  
  /users/{userId}:
    get:
      summary: Get user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Profile showed
        "404":
          description: User not found

  /users/{userId}/posts:
    post:
      summary: Create Post
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid

      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePostRequest'
      responses:
        "201": 
          description: Post created
        "404":
          description: User not found
    get:
      summary: Get posts published by some user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: Number of items to return
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: Feed showed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedPage'
        "404":
          description: User not found

  /users/{userId}/feed:
    get:
      summary: Get home feed for current user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: Number of items to return
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: Feed showed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedPage'
        "404":
          description: User not found

  /users/{userId}/chats:
    get:
      summary: List all chats
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: All chats listed
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ListChatsResponse"
        "404": 
          description: User not found

  /chats/{chatId}/messages:
    post:
      summary: Send message to chat
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        "201": 
          description: Message sent
        "400":
          description: Request error
    get:
      summary: Get all messages in chat
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          description: Number of items to return
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
        "404":
          description: Chat not found

components:
  schemas:
    CreatePostRequest:
      type: object
      properties: 
        title:
          type: string
        description:
          type: string
        imageUrl:
          type: string
      required:
        - title
        - description
    
    FeedPage:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Post"
      
    Post:
      type: object
      required: [id, authorId, text, createdAt]
      properties:
        id:
          type: string
          format: uuid
        authorId:
          type: string
          format: uuid
        text:
          type: string
        mediaUrls:
          type: array
          items:
            type: string
            format: uri
        createdAt:
          type: string
          format: date-time

    ListChatsResponse:
      type: object
      required: 
        - items
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ShortChatInfo"
        

    ShortChatInfo:
      type: object
      required: [title, chatId]
      properties:
        title:
          type: string
        chatId:
          type: string
          format: uuid

    Message:
      type: object
      required: [id, chatId, authorId, text, sentAt]
      properties:
        id:
          type: string
          format: uuid
        chatId:
          type: string
          format: uuid
        authorId:
          type: string
          format: uuid
        text:
          type: string
        sentAt:
          type: string
          format: date-time

    SendMessageRequest:
      type: object
      required: [authorId, text]
      properties:
        authorId:
          type: string
          format: uuid
        text:
          type: string
